module.exports = {
    name: 'een',
    description: "Elemental Energy",
    type: "sod-cdip",
    cards: ["Elemental HERO Rampart Blaster","Elemental HERO Tempest","Elemental HERO Wildedge","Elemental HERO Shining Flare Wingman","Elemental HERO Bladedge","Water Dragon","B.E.S. Tetran","Goldd, Wu-Lord of Dark World","VWXYZ-Dragon Catapult Cannon","Cyber Blader","Pot of Avarice","Queen's Knight","Jack's Knight","King's Knight","Chthonian Soldier","Rapid-Fire Magician","Broww, Huntsman of Dark World","Brron, Mad King of Dark World","Sillva, Warlord of Dark World","Feather Shot","Chthonian Alliance","Armed Changer","Hero Barrier","Chthonian Blast","Level Limit - Area A","Zure, Knight of Dark World","V-Tiger Jet","Blade Skater","Elemental HERO Wildheart","Reborn Zombie","W-Wing Catapult","Infernal Incinerator","Hydrogeddon","Oxygeddon","Etoile Cyber","Nanobreaker","Beiige, Vanguard of Dark World","Scarr, Scout of Dark World","Familiar-Possessed - Aussa","Familiar-Possessed - Eria","Familiar-Possessed - Hiita","Familiar-Possessed - Wynn","VW-Tiger Catapult","Dark World Lightning","Level Modulation","Ojamagic","Ojamuscle","Bonding - H2O","Branch!","Boss Rush","Gateway to Dark World","The Forces of Darkness","Dark Deal","Simultaneous Loss","Weed Out","The League of Uniform Nomenclature","Roll Out!","Chthonian Polymer","Feather Wind","Non-Fusion Area"],
    common: ["Zure, Knight of Dark World","V-Tiger Jet","Blade Skater","Elemental HERO Wildheart","Reborn Zombie","W-Wing Catapult","Infernal Incinerator","Hydrogeddon","Oxygeddon","Etoile Cyber","Nanobreaker","Beiige, Vanguard of Dark World","Scarr, Scout of Dark World","Familiar-Possessed - Aussa","Familiar-Possessed - Eria","Familiar-Possessed - Hiita","Familiar-Possessed - Wynn","VW-Tiger Catapult","Dark World Lightning","Level Modulation","Ojamagic","Ojamuscle","Bonding - H2O","Branch!","Boss Rush","Gateway to Dark World","The Forces of Darkness","Dark Deal","Simultaneous Loss","Weed Out","The League of Uniform Nomenclature","Roll Out!","Chthonian Polymer","Feather Wind","Non-Fusion Area"],
    rare: ["Queen's Knight","Jack's Knight","King's Knight","Chthonian Soldier","Rapid-Fire Magician","Broww, Huntsman of Dark World","Brron, Mad King of Dark World","Sillva, Warlord of Dark World","Feather Shot","Chthonian Alliance","Armed Changer","Hero Barrier","Chthonian Blast","Level Limit - Area A"],
    super: ["Elemental HERO Bladedge","Water Dragon","B.E.S. Tetran","Goldd, Wu-Lord of Dark World","VWXYZ-Dragon Catapult Cannon","Cyber Blader","Pot of Avarice"],
    ultra: ["Elemental HERO Rampart Blaster","Elemental HERO Tempest","Elemental HERO Wildedge","Elemental HERO Shining Flare Wingman"],
    ultimate: ["Elemental HERO Rampart Blaster","Elemental HERO Tempest","Elemental HERO Wildedge","Elemental HERO Shining Flare Wingman","Elemental HERO Bladedge","Water Dragon","B.E.S. Tetran","Goldd, Wu-Lord of Dark World","VWXYZ-Dragon Catapult Cannon","Cyber Blader","Pot of Avarice","Queen's Knight","Jack's Knight","King's Knight","Chthonian Soldier","Rapid-Fire Magician","Broww, Huntsman of Dark World","Brron, Mad King of Dark World","Sillva, Warlord of Dark World","Feather Shot","Chthonian Alliance","Armed Changer","Hero Barrier","Chthonian Blast","Level Limit - Area A"],
    price: 100,
    commonnum: 7,
    commonnum2: 1,
    rarenum: 1,
    supernum: 1,
    ultranum: 1,
    ultimatenum: 1,
}