module.exports = {
    name: 'taev',
    description: "Tactical Evolution",
    type: "taev-docs",
    cards: ["Gemini Summoner","Rainbow Dragon","Vennominaga the Deity of Poisonous Snakes","Frost and Flame Dragon","Elemental HERO Magma Neos","Cyberdark Impact!","Cranium Fish","Abyssal Kingshark","Mormolith","Il Blud","Vennominon the King of Poisonous Snakes","Chthonian Emperor Dragon","Crystal Seer","Desert Twister","Elemental HERO Darkbright","Necro Gardna","Elemental HERO Neos Alius","Aquarian Alessa","Lucky Pied Piper","Doom Shaman","Zombie Master","Fifth Hope","Mirror Gate","Blazewing Butterfly","Hunter Dragon","Grasschopper","Neo Space Pathfinder","Elemental HERO Marine Neos","Snake Rain","Doube Summon","Summoner's Art","Phalanx Pike","Symbols of Duty","Damage = Reptile","Snake Deity's Command","Common Charity","Spell Reclamation","Trap Reclamation","Ocean's Keeper","Thousand-Eyes Jellyfish","Fossil Tusker","Phantom Dragonray Bronto","Alien Shocktrooper","Volcanic Rat","Renge, Gatekeeper of Dark World","Venom Cobra","Chrysalis Pantail","Chrysalis Chicky","Chrysalis Larva","Chrysalis Mole","Venom Snake","Venom Boa","Venom Serpent","Goggle Golem","Dawnbreak Gardna","King Pyron","Shadow Delver","Flint Lock","Gravitic Orb","Phantom Cricket","Ritual Raven","Razor Lizard","Light Effigy","Dark Effigy","Neo-Spacian Marine Dolphin","Ojama Knight","Reverse of Neos","Convert Contact","Cocoon Party","NEX","Cocoon Rebirth","Venom Swamp","Venom Shot","Flint Missile","Creature Seizure","Amulet of Ambition","Broken Bamboo Sword","Hero Counterattack","Cocoon Veil","Snake Whistle","Rise of the Snake Deity","Ambush Fangs","Venom Burn","Destructive Draw","Shield Spear","Strike Slash","Gift Card","The Gift of Greed","Counter Counter"],
    common: ["Alien Shocktrooper","Volcanic Rat","Renge, Gatekeeper of Dark World","Venom Cobra","Chrysalis Pantail","Chrysalis Chicky","Chrysalis Larva","Chrysalis Mole","Venom Snake","Venom Boa","Venom Serpent","Goggle Golem","Dawnbreak Gardna","King Pyron","Shadow Delver","Flint Lock","Gravitic Orb","Phantom Cricket","Ritual Raven","Razor Lizard","Light Effigy","Dark Effigy","Neo-Spacian Marine Dolphin","Ojama Knight","Reverse of Neos","Convert Contact","Cocoon Party","NEX","Cocoon Rebirth","Venom Swamp","Venom Shot","Flint Missile","Creature Seizure","Amulet of Ambition","Broken Bamboo Sword","Hero Counterattack","Cocoon Veil","Snake Whistle","Rise of the Snake Deity","Ambush Fangs","Venom Burn","Destructive Draw","Shield Spear","Strike Slash","Gift Card","The Gift of Greed","Counter Counter"],
    rare: ["Hunter Dragon","Grasschopper","Neo Space Pathfinder","Elemental HERO Marine Neos","Snake Rain","Doube Summon","Summoner's Art","Phalanx Pike","Symbols of Duty","Damage = Reptile","Snake Deity's Command","Common Charity","Spell Reclamation","Trap Reclamation","Ocean's Keeper","Thousand-Eyes Jellyfish","Fossil Tusker","Phantom Dragonray Bronto"],
    supr: ["Necro Gardna","Elemental HERO Neos Alius","Aquarian Alessa","Lucky Pied Piper","Doom Shaman","Zombie Master","Fifth Hope","Mirror Gate","Blazewing Butterfly"],
    ultra: ["Vennominon the King of Poisonous Snakes","Chthonian Emperor Dragon","Crystal Seer","Desert Twister","Elemental HERO Darkbright"],
    secret: ["Gemini Summoner","Rainbow Dragon","Vennominaga the Deity of Poisonous Snakes","Frost and Flame Dragon","Elemental HERO Magma Neos","Cyberdark Impact!","Cranium Fish","Abyssal Kingshark","Mormolith","Il Blud"],
    ultimate: ["Vennominon the King of Poisonous Snakes","Chthonian Emperor Dragon","Crystal Seer","Desert Twister","Elemental HERO Darkbright","Necro Gardna","Elemental HERO Neos Alius","Aquarian Alessa","Lucky Pied Piper","Doom Shaman","Zombie Master","Fifth Hope","Mirror Gate","Blazewing Butterfly"],
    ghost: ["Rainbow Dragon"],
    price: 100,
    commonnum: 7,
    commonnum2: 1,
    rarenum: 1,
    supernum: 1,
    ultranum: 1,
    secretnum: 1,
    ultimatenum: 1,
    ghostnum: 1
}
