module.exports = {
    name: 'tdgs',
    description: "The Duelist Genesis",
    type: "taev-docs",
    cards: ["Avenging Knight Parshath","Hand of the Six Samurai","Cyber Shark","Charge of the Light Brigade","Splendid Venus","Fiendish Engine Omega","Ice Master","Toy Magician","Montage Dragon","Dark Hunter","Multiple Piece Golem","Nitro Warrior","Stardust Dragon","Red Dragon Archfiend","Goyo Guardian","Thought Ruler Archfiend","Emergency Teleport","Psychic Overload","Nitro Synchron","Sinister Sprocket","Twin-Barrel Dragon","Izanagi","Kinka-byo","Magical Android","Power Filter","Lightsworn Sabre","Unstable Evolution","Broken Blocker","Gladiator Beast War Chariot","Intercept","Counselor Lily","Kunai with Chain","Shield Warrior","Big Piece Golem","Dark Resonator","Handcuffs Dragon","Mind Master","Yamato-no-Kami","Fighting Spirit","De-Synchro","Graceful Revival","Defense Draw","Mind Over Matter","Herald of Orange Light","Izanami","Maiden of Macabre","Grapple Blocker","Telekinetic Charging Cell","The Tricky","Trap of Darkness","The Selection","Cold Enchanter","Turbo Booster","Quillbolt Hedgehog","Ghost Gardna","Small Piece Golem","Medium Piece Golem","Twin-Shield Defender","Jutte Fighter","Gonogo","Doctor Cranium","Krebons","Mind Protector","Psychic Commander","Psychic Snail","Telekinetic Shocker","Destructotron","Gladiator Beast Equeste","Jenis, Lightsworn Mender","Dharc the Dark Charmer","Mecha Bunny","Oyster Meister","Kunoichi","Beast of the Pharaoh","Noisy Gnat","Domino Effect","Junk Barrage","Battle Tuned","Lightwave Tuning","Psi-Station","Psi-Impulse","Sword of Kusanagi","Orb of Yasaka","Mirror of Yata","Geartown","Recycling Batteries","Book of Eclipse","Equip Shot","Remote Revenge","Spacegate","Synchro Deflector","Psychic Rejuvenation","Telepathic Power","Lightsworn Barrier","Judgment of Thunder","Fish Depth Charge","Needlebug Nest","Overworked","Tricky Spell 4"],
    common: ["Turbo Booster","Quillbolt Hedgehog","Ghost Gardna","Small Piece Golem","Medium Piece Golem","Twin-Shield Defender","Jutte Fighter","Gonogo","Doctor Cranium","Krebons","Mind Protector","Psychic Commander","Psychic Snail","Telekinetic Shocker","Destructotron","Gladiator Beast Equeste","Jenis, Lightsworn Mender","Dharc the Dark Charmer","Mecha Bunny","Oyster Meister","Kunoichi","Beast of the Pharaoh","Noisy Gnat","Domino Effect","Junk Barrage","Battle Tuned","Lightwave Tuning","Psi-Station","Psi-Impulse","Sword of Kusanagi","Orb of Yasaka","Mirror of Yata","Geartown","Recycling Batteries","Book of Eclipse","Equip Shot","Remote Revenge","Spacegate","Synchro Deflector","Psychic Rejuvenation","Telepathic Power","Lightsworn Barrier","Judgment of Thunder","Fish Depth Charge","Needlebug Nest","Overworked","Tricky Spell 4"],
    rare: ["Shield Warrior","Big Piece Golem","Dark Resonator","Handcuffs Dragon","Mind Master","Yamato-no-Kami","Fighting Spirit","De-Synchro","Graceful Revival","Defense Draw","Mind Over Matter","Herald of Orange Light","Izanami","Maiden of Macabre","Grapple Blocker","Telekinetic Charging Cell","The Tricky","Trap of Darkness","The Selection","Cold Enchanter"],
    supr: ["Nitro Synchron","Sinister Sprocket","Twin-Barrel Dragon","Izanagi","Kinka-byo","Magical Android","Power Filter","Lightsworn Sabre","Unstable Evolution","Broken Blocker","Gladiator Beast War Chariot","Intercept","Counselor Lily","Kunai with Chain"],
    ultra: ["Montage Dragon","Dark Hunter","Multiple Piece Golem","Nitro Warrior","Stardust Dragon","Red Dragon Archfiend","Goyo Guardian","Thought Ruler Archfiend","Emergency Teleport","Psychic Overload"],
    secret: ["Avenging Knight Parshath","Hand of the Six Samurai","Cyber Shark","Charge of the Light Brigade","Splendid Venus","Fiendish Engine Omega","Ice Master","Toy Magician"],
    ultimate: ["Montage Dragon","Dark Hunter","Multiple Piece Golem","Nitro Warrior","Stardust Dragon","Red Dragon Archfiend","Goyo Guardian","Thought Ruler Archfiend","Emergency Teleport","Psychic Overload"],
    ghost: ["Stardust Dragon"],
    price: 100,
    commonnum: 7,
    commonnum2: 1,
    rarenum: 1,
    supernum: 1,
    ultranum: 1,
    secretnum: 1,
    ultimatenum: 1,
    ghostnum: 1
}
