module.exports = {
    name: 'tp2',
    description: "Tournament Pack 2nd Season",
    type: "tourney",
    cards: ["Morphing Jar","Dragon Seeker","Giant Red Seasnake","Exile of the Wicked","Call of the Grave","Mikazukinoyaiba","Skull Guardian","Novox's Prayer","Dokurorider","Revival of Dokurorider","Beautiful Headhuntress","Sonic Maid","Mystical Sheep #1","Warrior of Tradition","Soul of the Pure","Dancing Elf","Turu-Purun","Dharma Cannon","Stuffed Animal","Spirit of the Books","Faith Bird","Takuhee","Maiden of the Moonlight","Queen of Autumn Leaves","Two-Headed King Rex","Garoozis","Crawling Dragon #2","Parrot Dragon","Sky Dragon","Water Magician"],
    common: ["Dancing Elf","Turu-Purun","Dharma Cannon","Stuffed Animal","Spirit of the Books","Faith Bird","Takuhee","Maiden of the Moonlight","Queen of Autumn Leaves","Two-Headed King Rex","Garoozis","Crawling Dragon #2","Parrot Dragon","Sky Dragon","Water Magician"],
    rare: ["Mikazukinoyaiba","Skull Guardian","Novox's Prayer","Dokurorider","Revival of Dokurorider","Beautiful Headhuntress","Sonic Maid","Mystical Sheep #1","Warrior of Tradition","Soul of the Pure"],
    super: ["Dragon Seeker","Giant Red Seasnake","Exile of the Wicked","Call of the Grave"],
    ultra: ["Morphing Jar"],
    price: 300,
    commonnum: 2,
    commonnum2: 1,
    rarenum: 1,
    supernum: 1,
    ultranum: 1,
}