module.exports = {
    name: 'tp5',
    description: "Tournament Pack 5th Season",
    type: "tourney",
    cards: ["Luminous Soldier","Big Shield Gardna","Magical Thorn","Luster Dragon","Needle Worm","Kycoo the Ghost Destroyer","Bazoo the Soul-Eater","Book of Life","Trap of Board Eraser","Goddess with the Third Eye","Jowgen the Spiritualist","Tornado Bird","Destruction Punch","Beastking of the Swamps","Versago the Destroyer","Mystical Sheep #1","Pyramid Turtle","Curse of Royal","Winged Sage Falcos","Dark Designator"],
    common: ["Goddess with the Third Eye","Jowgen the Spiritualist","Tornado Bird","Destruction Punch","Beastking of the Swamps","Versago the Destroyer","Mystical Sheep #1","Pyramid Turtle","Curse of Royal","Winged Sage Falcos","Dark Designator"],
    rare: ["Kycoo the Ghost Destroyer","Bazoo the Soul-Eater","Book of Life","Trap of Board Eraser"],
    super: ["Big Shield Gardna","Magical Thorn","Luster Dragon","Needle Worm"],
    ultra: ["Luminous Soldier"],
    price: 300,
    commonnum: 2,
    commonnum2: 1,
    rarenum: 1,
    supernum: 1,
    ultranum: 1,
}